apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "calipsoplus-portal.matchLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "calipsoplus-portal.matchLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
            - name: DATABASE_PORT
              value: {{ .Values.guacamole.db.port | quote }}
            - name: GUACD_HOSTNAME
              value: "guacd"
            - name: GUACD_PORT
              value: {{ .Values.guacd.port | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.guacamole.db.database | quote }}
            - name: MYSQL_HOSTNAME
              value: "guacamoledb"
            - name: MYSQL_PASSWORD
              value: {{ .Values.guacamole.db.mysqlPassword | quote }}
            - name: MYSQL_USER
              value: {{ .Values.guacamole.db.mysqlUser | quote }}
          image: "{{ .Values.guacamole.image.repository }}:{{ .Values.guacamole.image.tag }}"
          name: guacamole
          ports:
            - containerPort: {{ .Values.guacamole.targetPort }}
          resources: {}
          volumeMounts:
            - name: guac-script
              mountPath: /usr/local/tomcat/webapps/ROOT/
      restartPolicy: Always
      volumes: 
        - name: guac-script
          configMap:
            name: guacamole-script
            items:
              - key: guac_access.html
                path: index.html
status: {}
