kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: guacamole
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "calipsoplus-portal.matchLabels" . | nindent 6 }}
  ingress:
  -  from: []

