apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-login
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "calipsoplus-portal.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calipsoplus-portal.matchLabels" . | nindent 8 }}
    spec:
      containers:
      - image: eosc-pan-git.desy.de/calipsoplus/portal-kubernetes/mock-login:latest
        name: mocklogin
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: calipsoplus-registry-secret
status: {}
