apiVersion: v1
kind: Service
metadata:
  name: mock-login
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8000
  selector:
status:
  loadBalancer: {}
