apiVersion: apps/v1
kind: Deployment
metadata:
  name: calipsodb
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "calipsoplus-portal.matchLabels" . | nindent 6 }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "calipsoplus-portal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - mysqld
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: calipsoplus
            - name: MYSQL_PASSWORD
              value: {{ .Values.calipsoplus.db.mysqlPassword }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.calipsoplus.db.rootPassword }}
            - name: MYSQL_USER
              value: {{ .Values.calipsoplus.db.mysqlUser }}
          image: "{{ .Values.calipsoplus.db.image.registry }}:{{ .Values.calipsoplus.db.image.tag }}"
          name: calipso-mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
            - name: db-scripts
              mountPath: /docker-entrypoint-initdb.d/
      restartPolicy: Always
      imagePullSecrets:
        - name: calipsoplus-registry-secret
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: calipsodb-claim0
        - name: db-scripts
          configMap:
            name: calipsodb-scripts
            items:
              - key: calipsoplus.sql
                path: dump.sql
status: {}
