# Default values for calipsoplus-portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets:
  registry:
  username: 
  password:
  email:
nameOverride: ""
fullnameOverride: ""

calipsoplus:
  backend:
    image:
      repository: eosc-pan-git.desy.de:5555/calipsoplus/portal-kubernetes/web-back
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""
    port: 8001
    targetPort: 8000
  frontend:
    url: example.com
    image:
      repository: eosc-pan-git.desy.de:5555/calipsoplus/portal-kubernetes/web-front
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""
    port: 8000
    targetPort: 8000
  db: 
    database: calipsoplus
    mysqlUser: calipso
    mysqlPassword: calipsoplus
    rootPassword: calipsoadmin
    image:
      repository: mysql
      pullPolicy: IfNotPresent
      tag: "5.7.31"
    port: 3307
    targetPort: 3306
  oidc: 
    enabled: false
    client:
      id: calipsoplus-example
      secret: 'totally-secret'
      url: 'keycloak.example.com'
      authEndpoint: '../auth'
      tokenEndpoint: '../token'
      userEndpoint: '../userinfo'
      jwksEndpoint: '../certs'
      signAlgorithm: 'HS256'
  redirectUrl: 'https://calipsoplus.example.com/navigation'
  logoutUrl: 'https://calipsoplus.example.com'
  docker:
    host: 'calipso-docker-host.example.com'
    port: '2375'

jupyterhub:
  enabled: false
  url: 'jupyter.example.com'

guacamole:
  db:
    database: guacdb
    mysqlUser: guac
    mysqlPassword: guacamole
    rootPassword: guacadmin
    image:
      repository: mysql
      tag: '5.7.31'
    port: 3306
    targetPort: 3306
  image: 
    repository: guacamole/guacamole
    tag: '0.9.14'
  port: 8080
  targetPort: 8080
guacd:
  image:
    repository: guacamole/guacd
    tag: '0.9.14'
  port: 4822
  targetPort: 4822
mocklogin:
  image: 
    registry: eosc-pan-git.desy.de:5555/calipsoplus/mock-login
    tag: ""
  port: 8000
  targetPort: 8080

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
