apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocklogin
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "calipsoplus-portal.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calipsoplus-portal.matchLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.mocklogin.image.repository }}:{{ .Values.mocklogin.image.tag | default .Chart.AppVersion }}"
        name: mocklogin
        ports:
        - containerPort: {{ .Values.mocklogin.targetPort }}
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: calipsoplus-registry-secret
status: {}
