apiVersion: v1
kind: Service
metadata:
  name: mocklogin
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  ports:
    - name: login
      port: {{ .Values.mocklogin.port }}
      targetPort: {{ .Values.mocklogin.targetPort }}
  selector:
status:
  loadBalancer: {}
