apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cm
  labels: 
    {{- include "calipsoplus-portal.labels" . | nindent 4 }}
data:
  default.cnf: |
    [client]
    database = {{ .Values.calipsoplus.db.database }}
    host = calipsodb
    port = {{ .Values.calipsoplus.db.port }}
    user = {{ .Values.calipsoplus.db.mysqlUser }}
    password = {{ .Values.calipsoplus.db.mysqlPassword }}
    default-character-set = utf8
  guacamole.cnf: |
    [client]
    database = {{ .Values.guacamole.db.database }}
    host = guacamoledb
    port = {{ .Values.guacamole.db.port }}
    user = {{ .Values.guacamole.db.mysqlUser }}
    password = {{ .Values.guacamole.db.mysqlPassword }}
    default-character-set = utf8
