apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
    spec:
      containers:
        - args:
            - bash
            - -c
            - python manage.py migrate && gunicorn calipsoplus.wsgi -b 0:8000
          image: "{{ .Values.calipsoplus.backendImage.repository }}:{{ .Values.calipsoplus.backendImage.tag || .Chart.AppVersion }}"
          name: django01
          resources: {}
      imagePullSecrets:
        - name: calipsoplus-registry-key
      restartPolicy: Always
status: {}
