apiVersion: v1
kind: Service
metadata:
  name: backend
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: backend
    port: {{ .Values.calipsoplus.backend.port }}
    targetPort: {{ .Values.calipsoplus.backend.targetPort }}
  selector:
   {{ include "calipsoplus-portal.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}
