apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-cm
  labels: 
    {{- include "calipsoplus-portal.labels" . | nindent 4 }}
data:
  calipso: |
{{ .Files.Get "files/settings_calipso.py" | indent 4 }}
  kubernetes: |
{{  tpl (.Files.Get "files/settings_kubernetes.py") . | indent 4 }}
  settings: |
{{ .Files.Get "files/settings.py" | indent 4 }}
