apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "calipsoplus-portal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.guacamole.guacd.image.repository }}:{{ .Values.guacd.image.tag }}"
          name: guacd01
          ports:
            - containerPort: {{ .Values.guacd.targetPort }}
          resources: {}
      restartPolicy: Always
status: {}
