apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "calipsoplus-portal.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calipsoplus-portal.matchLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.guacd.image.repository }}:{{ .Values.guacd.image.tag }}"
          name: guacd
          ports:
            - containerPort: {{ .Values.guacd.targetPort }}
          resources: {}
      restartPolicy: Always
status: {}
