apiVersion: v1
kind: Service
metadata:
  name: guacd
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  ports:
    - name: guacd
      port: {{ .Values.guacd.port }}
      targetPort: {{ .Values.guacd.targetPort }}
  selector:
status:
  loadBalancer: {}
