apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-assets-cm
  labels:
    {{- include "calipsoplus-portal.labels" . | nindent 4 }}
binaryData:
  logo.jpg:
    {{ .Files.Get "files/desy-logo.jpg" | b64enc }}
