apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-assets-cm
  labels:
    {{- include "calipsoplus-portal.labels" . | nindent 4 }}
binaryData:
  logo:
    {{ .Files.Get "files/facility-logo.png" | b64enc }}
