apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      {{- include "calipsoplus-portal.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calipsoplus-portal.matchLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - npm
            - start
          image: "{{ .Values.calipsoplus.frontend.image.repository }}:{{ .Values.calipsoplus.frontend.image.tag | default .Chart.AppVersion }}"
          name: angular01
          resources: {}
          ports: 
            - name: http
              containerPort: {{ .Values.calipsoplus.frontend.targetPort }}
          volumeMounts:
            - name: assets
              mountPath: /assets/
            - name: environment-cm
              mountPath: /src/environments/
      restartPolicy: Always
      imagePullSecrets:
        - name: calipsoplus-registry-secret
      nodeSelector: {{ toJson .Values.calipsoplus.frontend.nodeSelector }}
      volumes:
        - name: assets
          configMap:
            name: frontend-assets-cm
            items:
              - key: logo.jpg
                path: logo.jpg
        - name: environment-cm
          configMap:
            name: frontend-environment-cm
            items:
              - key: environment.kubernetes.ts
                path: environment.ts
status: {}
