apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
    spec:
      containers:
        - args:
            - npm
            - start
          image: "{{ .Values.calipsoplus.frontendImage.repository }}:{{ .Values.calipsoplus.frontendImage.tag || .Chart.AppVersion }}"
          name: angular01
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: calipsoplus-registry-key
status: {}
