apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-environment-cm
  labels:
    {{- include "calipsoplus-portal.labels" . | nindent 4 }}
data:
  environment.kubernetes.ts: |
    {{ .Files.Get "files/environment.kubernetes.ts" | nindent 4 }}
