apiVersion: v1
kind: Service
metadata:
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
  name: frontend
spec:
  type: ClusterIP
  ports:
    - name: frontend
      port: {{ .Values.calipsoplus.frontend.port }}
      targetPort: {{ .Values.calipsoplus.frontent.targetPort }}
  selector:
   {{ include "calipsoplus-portal.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}
