apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole01  
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
    spec:
      containers:
        - env:
            - name: DATABASE_PORT
              value: {{ .Values.guacamole.db.port | quote }}
            - name: GUACD_HOSTNAME
              value: guacd
            - name: GUACD_PORT
              value: {{ .Values.guacd.port | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.guacamole.db.name }}
            - name: MYSQL_HOSTNAME
              value: db-guacamole
            - name: MYSQL_PASSWORD
              value: {{ .Values.guacamole.db.mysqlPassword }}
            - name: MYSQL_USER
              value: {{ .Values.guacamole.db.mysqlUser }}
          image: guacamole/guacamole:1.0.0
          name: guacamole01
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - name: guac-script
              mountPath: /usr/local/tomcat/webapps/ROOT/
      restartPolicy: Always
      volumes: 
        - name: guac-script
          configMap:
            name: guacamole-script
            items:
              - key: guac_access.html
              - path: index.html
status: {}
