apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
  name: guacamoledb
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  selector:
status:
  loadBalancer: {}
