apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamoledb-claim0
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
