apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamoledb
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "calipsoplus-portal.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- . | toYaml | trim | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - args:
          - mysqld
          - "--default-authentication-plugin=mysql_native_password"
        env:
          - name: MYSQL_DATABASE
            value: {{ .Values.guacamole.db.name | quote }}
          - name: MYSQL_USER
            value: {{ .Values.guacamole.db.mysqlUser | quote }}
          - name: MYSQL_PASSWORD
            value: {{ .Values.guacamole.db.mysqlPassword | quote }}
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.guacamole.db.rootPassword | quote }}
        image: "{{ .Values.guacamole.db.image.repository }}:{{ .Values.guacamole.db.image.tag }}"
        name: guacd-mysql0
        ports:
          - containerPort: 3306
        resources: {}
        volumeMounts:
          - name: guacamoledb-storage
            mountPath: /var/lib/mysql
          - name: guacamole-db
            mountPath: /docker-entrypoint-initdb.d/
      restartPolicy: Always
      volumes:
        - name: guacamoledb-storage
          persistentVolumeClaim:
            claimName: guacamoledb-claim0
        - name: guacamole-db
          configMap:
            name: guacamoledb-scripts
            items:
              - key: guacamole.sql
                path: dump.sql
status: {}
