apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: guacamole
  name: guacamole01  
  namespace: calipsoplus
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: guacamole
    spec:
      containers:
        - env:
            - name: DATABASE_PORT
              value: "3306"
            - name: GUACD_HOSTNAME
              value: guacd
            - name: GUACD_PORT
              value: "4822"
            - name: MYSQL_DATABASE
              value: guacdb
            - name: MYSQL_HOSTNAME
              value: db-guacamole
            - name: MYSQL_PASSWORD
              value: admincamps
            - name: MYSQL_USER
              value: admin
          image: guacamole/guacamole:1.0.0
          name: guacamole01
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - name: guac-script
              mountPath: /usr/local/tomcat/webapps/ROOT/
      restartPolicy: Always
      volumes: 
        - name: guac-script
          configMap:
            name: guacamole-script
            items:
              - key: guac_access.html
              - path: index.html
status: {}
