{{- if .Values.ingress.enabled -}}
{{- $fullName := include "calipsoplus-portal.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "calipsoplus-portal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: {{ .Values.calipsoplus.frontend.port }}
          - path: /guac/
            backend:
              serviceName: guacamole
              servicePort: {{ .Values.guacd.port }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: calipso-backend
  namespace: calipsoplus
  annotations:
    kubernetes.io/ingress.class: nginx-lb
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - backend:
          serviceName: backend
          servicePort: {{ .Values.calipsoplus.backend.port }}
        path: /services(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - calipsoplus.desy.de
    secretName: calipsoplus-ingress-tls
{{- end }}
