apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-login
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
    spec:
      containers:
      - image: eosc-pan-git.desy.de/calipsoplus/portal-kubernetes/mock-login:latest
        name: mocklogin01
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: calipsoplus-registry-key
status: {}
