apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-back
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
    spec:
      containers:
        - args:
            - bash
            - -c
            - python manage.py migrate && gunicorn calipsoplus.wsgi -b 0:8000
          image: eosc-pan-git.desy.de:5555/calipsoplus/portal-kubernetes/web-back:latest
          name: django01
          resources: {}
      imagePullSecrets:
        - name: calipsoplus-registry-key
      restartPolicy: Always
status: {}
