apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
    spec:
      containers:
        - args:
            - npm
            - start
          image: eosc-pan-git.desy.de:5555/calipsoplus/portal-kubernetes/web-front:latest
          name: angular01
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: calipsoplus-registry-key
status: {}
