apiVersion: v1
kind: Service
metadata:
  name: web-back
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: backend
    port: 8000
    targetPort: 8000
  selector:
status:
  loadBalancer: {}
