apiVersion: v1
kind: Service
metadata:
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
  name: web-front
spec:
  type: ClusterIP
  ports:
    - name: frontend
      port: 8001
      targetPort: 8001
  selector:
status:
  loadBalancer: {}
