{{- if .Values.calipsoplus.proxy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-cm
  labels: 
    {{- include "calipsoplus-portal.labels" . | nindent 4 }}
data:
  config: |
    upstream backend {
       ip_hash;
       server backend:{{ .Values.calipsoplus.backend.port }};
     }
    
    upstream frontend {
       ip_hash;
       server frontend:{{ .Values.calipsoplus.frontend.port }};
     }
     
    upstream guacamole {
       ip_hash;
       server guacamole:{{ .Values.guacamole.port }};
     }
    
     # HTTP server to redirect all 80 traffic to SSL/HTTPS
     # EDIT: let ingress handle https
     # portal
     server {
       
       listen 80;
       server_name proxy;
    
       location / {  
            proxy_pass http://frontend;
    		proxy_redirect          off;
    		proxy_set_header        Host            $host;
    		proxy_set_header        X-Real-IP       $remote_addr;
    		proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_connect_timeout   90;
    		proxy_send_timeout      90;
    		proxy_read_timeout      90;
    		proxy_buffer_size   16k;
    		proxy_buffers       32   16k;
    		proxy_busy_buffers_size 64k;
         }
        
        location /services {
    
    		if ($request_method = 'OPTIONS') {
           		add_header 'Access-Control-Allow-Origin' '*';
    
            	add_header 'Access-Control-Allow-Credentials' 'true';
            	add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    
           		add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    
            	add_header 'Access-Control-Max-Age' 86400;
            	add_header 'Content-Type' 'text/plain charset=UTF-8';
            	add_header 'Content-Length' 0;
            	return 204; break;
         	}
    	
         	if ($request_method = 'POST') {
            	add_header 'Access-Control-Allow-Origin' '*';
            	add_header 'Access-Control-Allow-Credentials' 'true';
            	add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            	add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
         	}
         	if ($request_method = 'GET') {
            	add_header 'Access-Control-Allow-Origin' '*';
            	add_header 'Access-Control-Allow-Credentials' 'true';
            	add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            	add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
         	}
    
            proxy_pass http://backend/;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
            #proxy_set_header Host $host;
         }
        
        location /guacamole {
             proxy_pass http://guacamole/;
             proxy_buffering off;
    		 proxy_redirect off;
             proxy_http_version 1.1;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection $http_connection;
             #proxy_set_header Host $host;
             access_log off;
         }
        
        location /ws {
    			proxy_cache off;
    			proxy_redirect off;
    			proxy_buffering off;
    			proxy_buffers 8 32k;
                proxy_buffer_size 64k;
    			proxy_http_version 1.1;
                proxy_set_header Host $http_host;
                proxy_set_header Connection "Upgrade";
    		 	proxy_set_header Upgrade $http_upgrade;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://guacd.calipsoplus.svc.cluster.local:4822;
    	    }
    
     }
{{- end }}
