apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamoledb
  labels: 
    {{- include "calipsoplus-portal.labels" . | nindent 4 }}
  creationTimestamp: null
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "calipsoplus-portal.matchLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "calipsoplus-portal.matchLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - mysqld
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: {{ .Values.guacamole.db.database }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.guacamole.db.mysqlPassword }}
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.guacamole.db.mysqlRootPassword }}
        - name: MYSQL_USER
          value: {{ .Values.guacamole.db.mysqlUser }}
        image: "{{ .Values.guacamole.db.image.repository }}:{{ .Values.guacamole.db.image.tag }}"
        imagePullPolicy: "{{ .Values.guacamole.db.image.pullPolicy }}"
        name: mysql0-guacd
        ports:
        - containerPort: {{ .Values.guacamole.db.targetPort }}
        resources: {}
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/dump.sql
          name: guacamoledb-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: guacamoledb-data
        persistentVolumeClaim:
          claimName: guacamoledb-claim0
status: {}
