apiVersion: v1
kind: Service
metadata:
  name: guacamoledb
  labels: {{ include "calipsoplus-portal.labels" . | nindent 4 }}
spec:
  ports:
    - name: guacamoledb
      port: {{ .Values.guacamole.db.port }}
      targetPort: {{ .Values.guacamole.db.targetPort }}
  selector:
   {{- include "calipsoplus-portal.matchLabels" . | nindent 4 }}
status:
  loadBalancer: {}
